import 'package:flutter/material.dart';
import 'screens/home_screen.dart';
import 'data/storage_service.dart';

// --- Hive Adapter Registration (Required for Persistence) ---
// Import the generated adapter files here:
// import 'models/emission_data.g.dart'; // NOTE: This file must be generated by 'flutter packages pub run build_runner build'

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Register Hive adapters if they were generated
  // try {
  //   Hive.registerAdapter(EmissionEntryAdapter());
  //   Hive.registerAdapter(DailyEmissionAdapter());
  // } catch (e) {
  //   // Only catch if adapters are already registered or if registration fails.
  //   debugPrint('Hive Adapter Registration skipped or failed: $e');
  // }
  
  // Initialize storage service once
  final storageService = StorageService();
  await storageService.init();
  
  runApp(EcoTrackApp(storageService: storageService));
}

class EcoTrackApp extends StatelessWidget {
  final StorageService storageService;
  const EcoTrackApp({super.key, required this.storageService});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'EcoTrack',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF00C853), // A vibrant green theme
          primary: const Color(0xFF00C853),
          secondary: const Color(0xFFFDD835),
        ),
        useMaterial3: true,
        fontFamily: 'Roboto',
      ),
      // Use a custom widget for initial routing/setup if needed,
      // but for now, directly point to HomeScreen
      home: EcoTrackSetup(storageService: storageService), 
    );
  }
}

class EcoTrackSetup extends StatefulWidget {
  final StorageService storageService;
  const EcoTrackSetup({super.key, required this.storageService});

  @override
  State<EcoTrackSetup> createState() => _EcoTrackSetupState();
}

class _EcoTrackSetupState extends State<EcoTrackSetup> {
  // Placeholder for initialization logic (e.g., Firebase, Auth, Loading)
  bool _isInitialized = false;

  @override
  void initState() {
    super.initState();
    _initializeApp();
  }

  void _initializeApp() async {
    // In a real app, this is where you'd initialize services like 
    // Hive/Firebase, load initial user data, etc.
    // The StorageService is already initialized in main(), but this could be a check.
    
    // Simulate necessary initialization delay 
    await Future.delayed(const Duration(seconds: 1)); 

    setState(() {
      _isInitialized = true;
    });
  }

  @override
  Widget build(BuildContext context) {
    if (!_isInitialized) {
      return const Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CircularProgressIndicator(),
              SizedBox(height: 16),
              Text('Loading EcoTrack...', style: TextStyle(fontSize: 16)),
            ],
          ),
        ),
      );
    }

    return HomeScreen(storageService: widget.storageService);
  }
}